### ISSUE TITLE
GraphiQL 1.0.0 beta Roadmap (monaco, redesign and plugin API!)

### ISSUE THREAD

**Issue by acao** [graphql/graphiql#1446]
Though the meta issue #983 summarizes all work that the new GraphiQL depends on, this issue is a roadmap for features that are GraphiQL *only*.

### `0.x.y`
- [x] e2e harness with Cypress and a starting suite
- [x] move from browserify to webpack build, improve webpack supprot with example configs
- [x] increase unit test coverage
- [x] numerous bugfixes
- [ ] backport a more IE compatible release, perhaps?
- [ ] e2e harness with Cypress and a nice suite to start with

### `1.0.0-alpha`
- [ ] #977 - full i18next!
- [X] #967 - full accessibility!
- [X] #1107 - React 16, drop support for React 15
- [X] #1204 - support GraphQL 15
- [ ] interfaces implementing interfaces
- [ ] #1359 - migrate to using React context, or another state management strategy
- [ ] React 16! Use deprecated class methods for now
- [ ] Get smarter with a core react context, provide `useGraphQLContext` hook, maybe with parsing and visitors/ast?
- [ ] Expose events interface to use internally and via plugins via `useReducer`, etc?
- [ ] Convert several smaller components to implement the hooks interface, use for existing functional components
- [ ] Begin with a 'plugins' array prop that renders Components that use context/reducer events and/or FCs that use hooks interface
- [ ] Adopt new monaco language mode, stabilize
- [ ] keymap/command customization to allow previous (sublime based) keymap, or new vscode-oriented keymap, or per-shortcut customization. Default keymap should have parity with last 0.x.y release?

### `1.0.0-beta`

- [ ] mostly stable API
- [ ] render middlewares
- [ ] full monaco support
