### ISSUE TITLE
GraphQL LanguageService 3.0.0 Roadmap

### ISSUE THREAD

**Issue by acao** [graphql/graphiql#1447]
## Package Re-organization
- `graphql-languageservice` (new) - a glue package for interface and types. meant to re-create the pattern of other vscode LS packages. [More details](https://github.com/graphql/graphiql/issues/1404)
- `graphql-language-service-interface`
- `graphql-language-service-parser`

With monaco, we can start working with a Language Server Protocol, which can be consumed by everyone on the web and in their IDE.

- [X] convert to TS
- [x] Symbols
- [x] interfaces implementing interfaces
- [x] Go To Definition (single document)
- [ ] Go To Definition (full workspace)
- [ ] Find References
- [ ] Go To Reference
- [ ] Plugins in the interface?
- [ ] Adopt upcoming 15.0.x features
- [ ] Replace `@babel/parser` with a language agnostic parser for `gql` template tags and other configurable patterns.
- [ ] Universal file system
- [x] Universal config, graphql-config?

**Comment by divyenduz** [comment]
> Go To Definition (full workspace)

This already works for a file that you open in the editor once. Maybe this is just about building the catch at first launch once.
