### ISSUE TITLE
graphiql 2 next steps roadmap

### ISSUE THREAD

**Issue by acao** [graphql/graphiql#2690]
I'm probably missing a lot of things here but just to get started. Please feel free to reorganize things as you please
# 2.0.x
- [ ] replace webpack 4 with webpack 4 at least if not full vite/esbuild for @graphiql/react & `graphiql`
- [ ] i18n
- [ ] more a11y improvements

# 2.x.y

- [ ] yaml, markdown, and html results view plugins
- [ ] query parser
- [ ] docs site 📚🔮
  - [ ] doc site setup
  - [ ] how-tos
  - [ ] examples
  - [ ] api docs
- [ ] easy vars?
- [ ] `renderGraphiQL`, middlewares and simple client-only docker image
  
 # 3.0.0
 
 - [ ] monaco
 - ...
  
# Todos

for this roadmap:
- [ ] link relevant issues
- [ ] create relevant discussions
- [ ] create relevant tickets

**Comment by leoloso** [comment]
Was there also the intention to incorporate an explorer widget, to click on fields and add them to the query, similar to [`OneGraph/graphiql-explorer`](https://github.com/OneGraph/graphiql-explorer)?

**Comment by acao** [comment]
@leoloso yes that will come in a later version for 2. see the graphiql explorer example if you want to enable the explorer plugin

**Comment by thomasheyenbrock** [comment]
@leoloso adding the explorer as a plugin will become even easier with https://github.com/graphql/graphiql/pull/2715

**Comment by leoloso** [comment]
Sounds awesome, thanks @thomasheyenbrock!

**Comment by LekoArts** [comment]
I'd also be interested in having https://github.com/OneGraph/graphiql-code-exporter as a first-class citizen plugin 👍

**Comment by toxsick** [comment]
> I'd also be interested in having https://github.com/OneGraph/graphiql-code-exporter as a first-class citizen plugin 👍

Same here, using it for a customer and without it I can not migrate to v2. Would even be even interested in contributing, but I need directions on this.

**Comment by LekoArts** [comment]
I time-boxed some time on the code exporter: https://github.com/LekoArts/graphiql/tree/code-exporter

![image](https://user-images.githubusercontent.com/16143594/188858474-c34e85f7-693f-4715-b483-3fd4c5598d2c.png)

It's not working correctly at the moment (see screenshot with the error), feel free to use that as a base.
