### ISSUE TITLE
GraphiQL Plugin Experience Improvements

### ISSUE THREAD

**Issue by acao** [graphql/graphiql#3331]
- [x] #3330
- [x] #3335
- [ ] #3328 
- [ ] migrate history feature to plugin (after #3130)
- [ ] migrate doc explorer to plugin
- [ ] `create-graphiql-plugin`
- [ ] add e2e test suite for consuming webpack example plugin builds
- [ ] add `pluginType` enum to `GraphiQLPlugin` definition
- [ ] new `pluginType`: variables
- [ ] variables json schema form plugin
- [ ] results `pluginType`
- [ ] network results tab plugin (breaking changes to `fetcher`?)
